apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
  - secretName: origin-cert-secret
  backend:
    serviceName: web
    servicePort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 labels:
   app: web
   keel.sh/policy: force
   keel.sh/match-tag: "true"
   keel.sh/trigger: poll
 annotations:
   keel.sh/pollSchedule: "@every 1m"
 name: web
spec:
 selector:
   matchLabels:
     app: web
 replicas: 2
 template:
   metadata:
     labels:
       app: web
   spec:
     containers:
     - image: index.docker.io/sheltertechsf/askdarcel-web:latest
       name: web
       resources:
         requests:
           cpu: 200m
           memory: 100Mi
         limits:
           cpu: 400m
           memory: 200Mi
       ports:
       - containerPort: 80
       env:
       - name: ALGOLIA_APPLICATION_ID
         valueFrom:
           secretKeyRef:
              name: algolia
              key: algolia-application-id
       - name: ALGOLIA_INDEX_PREFIX
         value: "staging"
       - name: ALGOLIA_READ_ONLY_API_KEY
         valueFrom:
           secretKeyRef:
              name: algolia
              key: algolia-read-only-api-key
       - name: API_URL
         value: "http://api.staging.svc.cluster.local:8080"
       - name: environment
         value: "production"
       - name: GOOGLE_API_KEY
         valueFrom:
           secretKeyRef:
              name: google
              key: frontend-google-api-key
       - name: PORT
         value: "80"
       - name: SERVER_NAME
         value: "staging.askdarcel.org"
       - name: MOHCD_SUBDOMAIN
         value: help
       - name: MOHCD_DOMAIN
         value: sfserviceguide
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: web
 name: web
spec:
 type: NodePort
 ports:
 - port: 80
 selector:
   app: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
 labels:
   app: api
   keel.sh/policy: force
   keel.sh/match-tag: "true"
   keel.sh/trigger: poll
 annotations:
   keel.sh/pollSchedule: "@every 1m"
 name: api
spec:
 selector:
   matchLabels:
     app: api
 replicas: 2
 template:
   metadata:
     labels:
       app: api
   spec:
     containers:
     - image: index.docker.io/sheltertechsf/askdarcel-api:latest
       name: api
       resources:
         requests:
           cpu: 200m
           memory: 512Mi
         limits:
           cpu: 400m
           memory: 1Gi
       ports:
       - containerPort: 8080
       env:
       - name: ALGOLIA_API_KEY
         valueFrom:
           secretKeyRef:
              name: algolia
              key: algolia-api-key
       - name: ALGOLIA_APPLICATION_ID
         valueFrom:
           secretKeyRef:
              name: algolia
              key: algolia-application-id
       - name: ALGOLIA_INDEX_PREFIX
         value: "staging"
       - name: ALGOLIA_READ_ONLY_API_KEY
         valueFrom:
           secretKeyRef:
              name: algolia
              key: algolia-read-only-api-key
       - name: DATABASE_PASSWORD
         valueFrom:
           secretKeyRef:
              name: database
              key: database-password
       - name: DATABASE_URL
         value: "postgres://10.34.96.19:5432/askdarcel"
       - name: DATABASE_USERNAME
         valueFrom:
           secretKeyRef:
              name: database
              key: database-username
       - name: GOOGLE_API_KEY
         valueFrom:
           secretKeyRef:
             name: google
             key: backend-google-api-key
       - name: SECRET_KEY_BASE
         valueFrom:
           secretKeyRef:
              name: secret-key
              key: secret-key-base
       - name: AIRTABLE_API_KEY
         valueFrom:
           secretKeyRef:
             name: airtable
             key: airtable-api-key
     restartPolicy: Always
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: askdarcel-algolia-reindex
  labels:
    app: askdarcel-algolia-reindex
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: index.docker.io/sheltertechsf/askdarcel-api:latest
            name: askdarcel-algolia-reindex
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 400m
                memory: 1Gi
            args:
            - /bin/sh
            - -c
            - cd /home/app/webapp && bundle exec rake algolia:reindex && exit
            env:
            - name: ALGOLIA_API_KEY
              valueFrom:
                secretKeyRef:
                   name: algolia
                   key: algolia-api-key
            - name: ALGOLIA_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                   name: algolia
                   key: algolia-application-id
            - name: ALGOLIA_INDEX_PREFIX
              value: "staging"
            - name: ALGOLIA_READ_ONLY_API_KEY
              valueFrom:
                secretKeyRef:
                   name: algolia
                   key: algolia-read-only-api-key
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: database
                   key: database-password
            - name: DATABASE_URL
              value: "postgres://10.34.96.19:5432/askdarcel"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                   name: database
                   key: database-username
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google
                  key: backend-google-api-key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                   name: secret-key
                   key: secret-key-base
            - name: AIRTABLE_API_KEY
              valueFrom:
                secretKeyRef:
                   name: airtable
                   key: airtable-api-key
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: api
 name: api
spec:
 type: ClusterIP
 ports:
 - port: 8080
 selector:
   app: api
